version: '3.1'
services:
  db:
    image: postgres:14.2
    restart: always
    environment:
      - POSTGRES_USER=a500
      - POSTGRES_PASSWORD=secret
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
